-- Baseline schema for the notification service (jari_notification).
-- Derived from com.example.jari.notification.entity.Notification against a clean database.
--
-- user_id holds an identity-service user id and is deliberately NOT a foreign key:
-- that table lives in another service's database.
--
-- Forward-only: never edit this file once applied. Add V2__*.sql instead.

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(255) NOT NULL,
    message    VARCHAR(255) NOT NULL,
    type       VARCHAR(255),
    read       BOOLEAN      NOT NULL,
    link       VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);
