-- Baseline schema for the project service (jari_project).
-- Derived from com.example.jari.project.entity.Project against a clean database.
--
-- lead_user_id holds an identity-service user id. It is deliberately NOT a foreign key:
-- that table lives in another service's database, and this service must not reach into it.
--
-- Forward-only: never edit this file once applied. Add V2__*.sql instead.

CREATE TABLE projects
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key          VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    avatar_url   VARCHAR(255),
    lead_user_id BIGINT,
    active       BOOLEAN      NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6),
    CONSTRAINT uk_projects_key UNIQUE (key)
);
