-- Baseline schema for the identity service (jari_user).
-- Derived from com.example.jari.user.entity.User against a clean database, so this
-- describes what the entity defines rather than the residue of prior ddl-auto: update runs.
--
-- Forward-only: never edit this file once applied. Add V2__*.sql instead.

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    username   VARCHAR(255),
    avatar_url VARCHAR(255),
    active     BOOLEAN      NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username)
);
