-- Baseline schema for the task service (jari_task).
-- Derived from com.example.jari.task.entity.Task against a clean database.
--
-- KNOWN DEFECT, recorded faithfully rather than fixed here: `key` has no unique
-- constraint, so nothing stops two tasks sharing "PROJ-123". The per-project key
-- counter that makes uniqueness enforceable belongs to a later phase; adding the
-- constraint now would mean this baseline no longer describes the current entities.
--
-- project_id / reporter_id / assignee_id reference rows in other services' databases
-- and are deliberately NOT foreign keys.
--
-- Forward-only: never edit this file once applied. Add V2__*.sql instead.

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         VARCHAR(255) NOT NULL,
    summary     VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    task_order  INTEGER,
    priority    INTEGER,
    type        INTEGER,
    status      VARCHAR(255),
    project_id  BIGINT,
    reporter_id BIGINT,
    assignee_id BIGINT,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6)
);
