-- Adds comments on a task. Forward-only per the rule established in
-- add-schema-migrations: V1__baseline.sql is never edited, only superseded.
--
-- author_id holds an identity-service user id, resolved from the gateway-
-- injected identity header at creation time. Not a foreign key, for the same
-- reason task_id could be but deliberately isn't cross-referenced elsewhere in
-- this baseline: the referenced table lives in another service's database.

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT       NOT NULL,
    author_id  BIGINT       NOT NULL,
    body       VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_task_id ON comments (task_id);
